# Generated by Django 5.0.6 on 2024-06-20 16:52

import transactions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='scheduled_time',
            field=models.DateTimeField(help_text='The scheduled time of the transaction.', validators=[transactions.validators.FutureDateValidator()], verbose_name='Scheduled Time'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='positive_amount', violation_error_message='The amount must be positive. Got %(show_value)s.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='sender_and_receiver_are_different', violation_error_message='Sender and receiver cannot be the same.'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='positive_balance', violation_error_message='The balance must always be positive. Got %(show_value)s.'),
        ),
    ]
